### PR TITLE
Fix SLIP encoder to ensure proper escaping for the last byte

### PR DESCRIPTION
**Pull request by suzuki-toshihir0**
# Problem

In the current implementation, `FEND` (0xC0) and `FESC` (0xDB) are not properly escaped if they are in the last byte of input.

https://github.com/arkedge/slippers/blob/6eae5b95b6c340b6dca7cc85d0655e57e336e349/src/lib.rs#L338-L342

# Fix

- Maked sure to check `self.escaped` even if the buffer is empty. 
- Added test cases.

### CODE REVIEW

**Comment by thvdveld** [comment]
Thank you very much for adding this!

**Comment by suzuki-toshihir0** [comment]
@thvdveld Thank you for merging! Could you update the version and `cargo publish` ?

**Comment by thvdveld** [comment]
I published it yesterday but forgot to push to GitHub.

**Comment by suzuki-toshihir0** [comment]
Oh, I confirmed the version bump! Thank you.

**Pull request merged**
